### ISSUE TITLE
Uncaught Error: Class 'greeny\MailLibrary\Contact' not found in

### ISSUE THREAD

**Issue by ghost** [php-mail-client/Client#25]
Hello,

the application can`t find greeny\MailLibrary\Contact in the folders.
 i just inserted

	use greeny\MailLibrary\Drivers\ImapDriver;
	use greeny\MailLibrary\Connection;
	use greeny\MailLibrary\Mail;
	use greeny\MailLibrary\Mailbox;
	use greeny\MailLibrary\Contact;
	use greeny\MailLibrary\ContactList;

at the start.
To echo everything out, testwise - i wrote this little test for:

$driver = new ImapDriver('ahhwahhah@gawkg.de', 'awgahiwiNI"N82ng', 'mailserver.de', 993, TRUE);
	$connection = new Connection($driver);
	$connection->getMailboxes();
	
	$mailbox = $connection->getMailbox('INBOX.Trash');
	$selection = $mailbox->getMails();

	$selection->limit(5);
	
	foreach($selection as $mail) 
	{
		?>
		<div style="width: 500px; height: 100px; overflow-y: scroll; margin-bottom: 20px;">
			<?php echo $mail->xRequestFrom; ?>
		</div>
		<?php
	}

**Comment by aharabara** [comment]
@1d0navan  issue is related to custom autoloader in loader.php . Seems that on master it is fixed

**Comment by ghost** [comment]
okay, im looking into it.

**Comment by 200MPH** [comment]
I pulled from master branch and it's definitely works.

**Comment by mschrading** [comment]
I still get this problem when i implement it with: composer require php-mail-client/client
and it version 3.2.2! I think it's the master branch... but there is also a version 3.2.2a !!

How to fix this problem: [Uncaught Error: Class 'greeny\MailLibrary\Contact' not found] ??

Thanks a lot

**Comment by srees4** [comment]
> I still get this problem when i implement it with: composer require php-mail-client/client and it version 3.2.2! I think it's the master branch... but there is also a version 3.2.2a !!
> 
> How to fix this problem: [Uncaught Error: Class 'greeny\MailLibrary\Contact' not found] ??
> 
> Thanks a lot

Same error on my end. When I do composer require php-mail-client/client it downloads ^3.2, so I had to adjust it to use dev-master and problem solved my issue.

**Comment by 200MPH** [comment]
OK the branch dev and master are different.
Dev contains PSR-4 autoloader therfore above declaration works.

Two options:
1. Use this namespaces instead: "greeny\maillibrary\contact"
2. Checkout to dev branch and pull.
